"""empty message

Revision ID: 8fc02c170a32
Revises: ae690c55de0b
Create Date: 2020-08-14 21:18:35.746333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc02c170a32'
down_revision = 'ae690c55de0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('storage_shop_id_fkey', 'storage', type_='foreignkey')
    op.create_foreign_key(None, 'storage', 'shop', ['shop_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.create_foreign_key('storage_shop_id_fkey', 'storage', 'shop', ['shop_id'], ['id'])
    # ### end Alembic commands ###
