"""add_storage

Revision ID: ae690c55de0b
Revises: d00f08464fac
Create Date: 2020-08-14 21:07:39.054098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae690c55de0b'
down_revision = 'd00f08464fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('network', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'network', 'shop', ['shop_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('shop_network_id_fkey', 'shop', type_='foreignkey')
    op.drop_column('shop', 'network_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('network_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('shop_network_id_fkey', 'shop', 'network', ['network_id'], ['id'])
    op.drop_constraint(None, 'network', type_='foreignkey')
    op.drop_column('network', 'shop_id')
    op.drop_table('storage')
    # ### end Alembic commands ###
